
---

- hosts: all
  become: true
  tasks:

  - name: install apache package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php package
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: add php package
    yum:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"

