---

- hosts: all
  become: true
  pre_tasks:

  - name: install update (CentOS)
    tags: always
    yum:
          update_only: yes
          update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install update (CentOS)
    apt:
        update_only: yes
        update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: workstation
  bacome: true
    tasks:

   - name: install unzip
     package: 
      name: unzip

   - name: install terraform
     unarchive:
     src:
     dest: /usr/local/bin
     remote_src: yes
     mode: 0755
     ownder: root
     group: root  

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php package
    tags: apache, apache2, ubuntu
    apt:
      name:
        apache2
        libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php package
    tags: httpd
    yum:
      name:
        httpd
        php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: copy default html file for site
    tags: apache, apache2, httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package
    tags: db,mariadb,ubunut
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb package
    tags: db,mariabd,centos
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

